name = "discord"
version = "0.2.0"
display-name = "Discord"
author = "SleepyKitten"
description = "Discord like theme"
repository = "https://github.com/sleepy-kitten/lapce-discord"
color-themes = ["discord.toml"]
